services:
  bot:
    image: ghcr.io/brokikrul/bot-discord:latest
    container_name: bot-discord
    restart: unless-stopped
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 3 * * * *
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_CONTAINERS=bot-discord
